In [1]:
import pandas as pd

In [12]:
df=pd.read_csv('Bike_Rental_data.csv')
df.head()

C:\Users\boosa\AppData\Local\Temp\ipykernel_20428\3225573114.py:1: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('Bike_Rental_data.csv')

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,0.992410,01-01-2011,springer,2011,1,-0.009452,No,5.990616,No work,Clear,0.24,0.2879,0.81,0,3,13,15.999019
1,2.004157,01-01-2011,springer,2011,1,1.007925,No,5.996162,No work,Clear,0.22,0.2727,0.8,0,8,32,40.004970
2,2.984610,01-01-2011,springer,2011,1,1.993083,No,6.004768,No work,Clear,0.22,0.2727,?,0,5,27,32.004786
3,3.993251,01-01-2011,springer,2011,1,2.991451,No,5.980473,No work,Clear,0.24,0.2879,0.75,0,3,10,12.999856
4,4.990763,01-01-2011,springer,2011,1,4.024688,No,5.984412,No work,Clear,0.24,0.2879,0.75,0,0,1,1.002089

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100576 entries, 0 to 100575
Data columns (total 17 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   instant     100576 non-null  float64
 1   dteday      100576 non-null  object
 2   season      100576 non-null  object
 3   yr          100576 non-null  object
 4   mnth        100576 non-null  object
 5   hr          100576 non-null  float64
 6   holiday     100576 non-null  object
 7   weekday     100576 non-null  float64
 8   workingday  100576 non-null  object
 9   weathersit  100576 non-null  object
 10  temp        100576 non-null  object
 11  atemp       100576 non-null  object
 12  hum         100576 non-null  object
 13  windspeed   100576 non-null  object
 14  casual      100576 non-null  object
 15  registered  100576 non-null  object
 16  cnt         100576 non-null  float64
dtypes: float64(4), object(13)
memory usage: 13.0+ MB

In [16]:
df.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [26]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import joblib
import numpy as np

# Load dataset with explicit data types
df = pd.read_csv("Bike_Rental_data.csv", low_memory=False)

# Replace '?' and other unknown values with NaN
df.replace("?", np.nan, inplace=True)

# Convert numeric columns properly
numeric_cols = ["yr", "mnth", "hr", "weekday", "temp", "atemp", "hum", "windspeed", "casual", "registered", "cnt"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")  # Convert to numbers, set invalid values to NaN

# Drop non-numeric columns before applying median
df_numeric = df[numeric_cols]  # Extract only numeric columns
df_numeric.fillna(df_numeric.median(), inplace=True)  # Replace NaNs with median

# Merge back with the original DataFrame
df[numeric_cols] = df_numeric

# Encode categorical columns properly
label_encoders = {}
categorical_cols = ["season", "holiday", "workingday", "weathersit"]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))  # Convert to string before encoding
    label_encoders[col] = le

# Define features (X) and target (y)
X = df.drop(columns=["cnt", "dteday"])  # Removing non-numeric or irrelevant columns
y = df["cnt"]  # Target variable

# Split data into train & test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Save model
joblib.dump(model, "bike_rental_model.pkl")
print("Model saved as bike_rental_model.pkl")

C:\Users\boosa\AppData\Local\Temp\ipykernel_20428\1272171986.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_numeric.fillna(df_numeric.median(), inplace=True)  # Replace NaNs with median

Model saved as bike_rental_model.pkl